version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.8
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    environment:
      GOARCH: amd64
      GOOS: linux
    steps:
      - restore_cache:
          keys:
            - go-bin
      - run: go get github.com/golang/dep/cmd/dep
      - run: go get github.com/tcnksm/ghr
      - save_cache:
          paths:
            - /go/bin
            - /go/src/github.com/golang/dep/cmd/dep
            - /go/src/github.com/tcnksm/ghr
          key: go-bin
      - checkout
      - restore_cache:
          keys:
            - dhop-dep-{{ checksum "Gopkg.lock" }}
            - dhop-dep-
      - run: dep ensure
      - save_cache:
          paths:
            - /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}/cmd/vendor
          key: dhop-dep-{{ checksum "Gopkg.lock" }}
      - run: go build --ldflags '-s -w' -o "bin/dhop-${GOARCH}-${GOOS}" cmd/*.go
      - persist_to_workspace:
          root: cmd
          paths:
            - bin
  deploy:
    docker:
      - image: circleci/golang:1.8
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - attach_workspace:
          at: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}/cmd/bin
      - run: ghr -t $GITHUB_TOKEN -u $CIRCLE_PROJECT_USERNAME -r $CIRCLE_PROJECT_REPONAME --replace $CIRCLE_TAG bin/
workflows:
  version: 2
  build-n-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /.*/
#           branches:
#             ignore: /.*/
